version: '3'

services:
  database:
    build: ./DataBase
    environment:
      MYSQL_DATABASE: trabajoarqui
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    ports:
      - "3306:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root"]
      timeout: 20s
      retries: 10
  front:
    build: ./Pagina
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "3000:3000"
  back:
    build: ./mvc-go
    restart: on-failure
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "8090:8090"