version: '3'

services:
  mysql:
    build: ./db
    environment:
      MYSQL_DATABASE: trabajoarqui
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    ports:
      - "3306:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root"]
      timeout: 20s
      retries: 10
  frontend:
    build: ./Pagina
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "3000:3000"
  backend:
    build: ./mvc-go
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8090:8090"